name: Run main.py every minute

on:
  push:                 # runs on every push
  schedule:
    - cron: '*/1 * * * *'  # runs every 1 minute
  workflow_dispatch:    # allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Notify start
        run: echo "✅ Workflow started at $(date)"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Optional: Install dependencies if needed
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set SESSION_ID environment variable
        run: echo "SESSION_ID=${{ secrets.SESSION_ID }}" >> $GITHUB_ENV

      - name: Run script
        run: python3 main.py
